spring:
  datasource:
    url: jdbc:h2:mem:cloudvendordb
    driverClassName: org.h2.Driver
    username: admin
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: "health, beans, metrics"
      base-path: "/management-dashboard"
  endpoint:
    health:
      show-details: always

dummyService:
  port: 8081
  address: 127.0.0.1
